"""add phone number

Revision ID: 42fb1321daf3
Revises: 7ea2e9da68a1
Create Date: 2024-01-08 10:32:01.964237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42fb1321daf3'
down_revision: Union[str, None] = '7ea2e9da68a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    
   
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('users', 'phone_number')
    
